### ISSUE TITLE
Правки к статьям (@SneakBug8)

### ISSUE THREAD

**Issue by Romjkez** [SneakBug8/mini_learning#1]
## Правки для @SneakBug8 

- [x] Одна из картинок в рамках "1961" не отображается: https://github.com/SneakBug8/mini_learning/blob/main/2_history/source.md#1961
- [x] Также в "1961" говорится: `Так появляется легендарный Mini Cooper 997 с двигателем 55 л.с.`, при этом в тесте верный ответ про мощность двигателя - 50 л.с. 
- [x] в вопросе `В какой стране проходит ралли Монте-Карло?` слово "стране" наверно стоит заменить на "странах", чтобы не вводить в заблуждение лишний раз по поводу кол-ва ответов
- [x] В рамках "1969" также висят 2 битые ссылки на картинки: https://github.com/SneakBug8/mini_learning/blob/main/2_history/source.md#1969
- [x] В 1986 еще 2 битые ссылки на картинки: https://github.com/SneakBug8/mini_learning/blob/main/2_history/source.md#1986
- [x] В 1994 в конце битая ссылка: https://github.com/SneakBug8/mini_learning/blob/main/2_history/source.md#1994
- [x] 1998: битая ссылка в конце: https://github.com/SneakBug8/mini_learning/blob/main/2_history/source.md#1998
- [x] 1999: битая ссылка в начале: https://github.com/SneakBug8/mini_learning/blob/main/2_history/source.md#1999
- [x] 2001: все ссылки битые: https://github.com/SneakBug8/mini_learning/blob/main/2_history/source.md#2001
- [x] 2004: битая ссылка: https://github.com/SneakBug8/mini_learning/blob/main/2_history/source.md#2004
- [x] 2006: битая ссылка: https://github.com/SneakBug8/mini_learning/blob/main/2_history/source.md#2006
- [x] 2007: битая ссылка: https://github.com/SneakBug8/mini_learning/blob/main/2_history/source.md#2007
- [x] 2010: битая ссылка: https://github.com/SneakBug8/mini_learning/blob/main/2_history/source.md#2010
- [x] 2011: битые ссылки: https://github.com/SneakBug8/mini_learning/blob/main/2_history/source.md#2011
- [x] Дополнить материалы тестами (начиная с 2000 года)
- [ ] В рамках раздела 5 предлагаю что-нибудь найти про иерархию в MINI (можно мировую, не только РФ), как компания находит дилеров и взаимодействует с ними, какие требования предъявляет (имею в виду внешний вид автосалонов, к примеру) и как и когда вообще появился MINI в России
